### ISSUE TITLE
[feature request] RWLock

### ISSUE THREAD

**Issue by thefab** [ajdavis/toro#8]
What about a RWLock primitive for toro ?

http://en.wikipedia.org/wiki/Readers%E2%80%93writer_lock

If you are interested, maybe I can work on it.

I plan to use toro for:
https://github.com/thefab/restful-distributed-lock-manager

**Comment by ajdavis** [comment]
Closed via https://github.com/ajdavis/toro/commit/244b0828e781fedb282ebe9410594d7c2ec93fd0.
